accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/<int:pk>/', views.profile_edit, name='profile_edit'),
    path('profile/password_change/', views.password_change, name='password_change'),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('subscribe/delete/<int:subscription_pk>/', views.subscribe_delete, name='subscribe_delete'),
    path('subscribe/manage/<int:pk>/', views.subscribe_manage, name='subscribe_manage'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('list/<int:pk>/', views.postlist, name='postlist'),
    path('<int:pk>/', views.post_detail, name='post_detail'),
    path('edit/<int:pk>/', views.postedit, name='postedit'),
    path('write/', views.postwrite, name='postwrite'),
    path('delete/<int:pk>/', views.postdelete, name='postdelete'),
    path('search/<int:pk>/', views.postlist, name='postsearch'),
    path('comment_add/', views.comment_add, name='comment_add'),
    path('comment_delete/<int:comment_pk>/', views.comment_delete, name='comment_delete'),
    path('comment_edit/<int:pk>/', views.comment_edit, name='comment_edit'),
    path('recomment_add/', views.recomment_add, name='recomment_add'),
    path('recomment_delete/<int:recomment_pk>/', views.recomment_delete, name='recomment_delete'),
    path('recomment_eidt/<int:pk>/', views.recomment_edit, name='recomment_edit'),
    path('other/<int:other_pk>/', views.other_postlist, name='other_postlist'),
]

tech_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('board/', include('board.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager

class CustomUserManager(UserManager):
    def _create_user(self, username, email, password, **extra_fields):
        if not email:
            raise ValueError('이메일은 필수입니다.')
        email = self.normalize_email(email)
        user = self.model(
            username = username,
            email = email,
            **extra_fields,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_user(self, username, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(username, email, password, **extra_fields)
    
    def create_superuser(self, username, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return super()._create_user(username, email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=50, unique=True, null=False)
    email = models.EmailField(max_length=100, unique=True, null=False)
    nickname = models.CharField(max_length=50, unique=True, null=False)
    phone = models.CharField(max_length=50, unique=True, blank=True, null=True)
    development_field = models.CharField(max_length=50, null=False)
    profile_image = models.ImageField(upload_to='accounts/%Y/%m/%d/', blank=True, null=True)
    joined_date = models.DateTimeField(auto_now_add=True, null=False)
    subscriptions = models.ManyToManyField('User', blank=True)

    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'nickname']

    objects = CustomUserManager()

    def __str__(self):
        return self.nickname
    
    def get_short_name(self):
        return self.nickname
    
    def get_full_name(self):
        return self.nickname
    
    def get_absolute_url(self):
        return f'/accounts/profile/{self.pk}/'
    
    class Meta:
        verbose_name = '사용자'
        verbose_name_plural = '사용자'

accounts/forms.py
from django import forms

from .models import User
    
class UserLoginForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['email', 'password']

    
class SubscribeForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['subscriptions']

accounts/views.py
from typing import Any
from django.core.handlers.wsgi import WSGIRequest
from django.template.response import TemplateResponse
from django.views import View
from django.views.generic import CreateView, UpdateView, ListView, DeleteView
from django.shortcuts import render, redirect
from django.forms.models import BaseModelForm
from django.http import HttpRequest, HttpResponse
from django.db.models import Q
from django.contrib import auth
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.hashers import check_password
import re

from .models import User
from .forms import SubscribeForm

class CustomLoginView(LoginView):
    template_name = 'accounts/login.html'
    next_page = ''

    def post(self, request: HttpRequest, *args, **kwargs):
        return super(CustomLoginView, self).post(request, *args, **kwargs)

class SignUpView(CreateView):
    model = User
    template_name = 'accounts/signup.html'
    fields = ['username', 'nickname', 'email', 'password', 'development_field', 'phone']

    def post(self, request: HttpRequest, *args, **kwargs):
        username = request.POST.get('username')
        context = {}
        if not username:
            context['notice'] = '유저명은 필수 입력 값입니다.'
            return render(request, 'accounts/signup.html', context)
        nickname = request.POST.get('nickname')
        if not nickname:
            context['notice'] = '닉네임은 필수 입력 값입니다.'
            return render(request, 'accounts/signup.html', context)
        email = request.POST.get('email')
        if not email:
            context['notice'] = '이메일은 필수 입력 값입니다.'
            return render(request, 'accounts/signup.html', context)
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        message = passwordValidator(password1, password2)
        if message:
            context['notice'] = message
            return render(request, 'accounts/signup.html', context)
        development_field = request.POST.get('development_field')
        if not development_field:
            context['notice'] = '개발 분야은 필수 입력 값입니다.'
            return render(request, 'accounts/signup.html', context)
        phone = request.POST.get('phone')
        user = User(username=username, nickname=nickname, email=email, development_field=development_field, phone=phone)
        user.set_password(password1)
        user.save()
        return redirect('/accounts/login')
    

class CustomLogoutView(LoginRequiredMixin, LogoutView):
    login_url = '/accounts/login/'
    next_page = '/accounts/login/'


class ProfileView(LoginRequiredMixin, View):
    login_url = '/accounts/login/'

    def get(self, request):
        return render(request, 'accounts/profile.html')
    

class ProfileEditView(LoginRequiredMixin, UpdateView):
    login_url = '/accounts/login/'
    model = User
    fields = ['nickname', 'development_field', 'phone', 'profile_image']
    template_name = 'accounts/profile_edit.html'
    
    success_url = '/accounts/profile/'

    def post(self, request: HttpRequest, *args, **kwargs):
        context = {}
        nickname = request.POST.get('nickname')
        if not nickname:
            context['notice'] = '닉네임은 필수 입력 값입니다.'
            return render(request, 'accounts/profile_edit.html', context)
        development_field = request.POST.get('development_field')
        if not development_field:
            context['notice'] = '개발 분야은 필수 입력 값입니다.'
            return render(request, 'accounts/profile_edit.html', context)
        phone = request.POST.get('phone')
        profile_image = request.FILES.get('profile_image')
        user = User.objects.get(pk = request.user.pk)
        user.nickname = nickname
        user.development_field = development_field
        user.phone = phone
        if profile_image:
            user.profile_image = profile_image
        user.save()
        return redirect('/accounts/profile/')


class PasswordChangeView(View):

    def get(self, request):
        return render(request, 'accounts/password_change.html')
    
    def post(self, request):
        cur_password = request.POST.get('cur_password')
        context = {}
        if not check_password(cur_password, request.user.password):
            context['notice'] = '현재 비밀번호가 일치하지 않습니다.'
            return render(request, 'accounts/password_change.html', context)
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        message = passwordValidator(password1, password2)
        if message:
            context['notice'] = message
            return render(request, 'accounts/password_change.html', context)
        user = request.user
        user.set_password(password1)
        user.save()
        auth.logout(request)
        return redirect('/accounts/login')
    

class SubscribeView(LoginRequiredMixin, ListView):
    model = User
    form_class = SubscribeForm
    login_url = '/accounts/login/'


class SubscribeDeleteView(LoginRequiredMixin, DeleteView):
    model = User
    form_class = SubscribeForm
    login_url = '/accounts/login/'

    def post(self, request: HttpRequest, *args, **kwargs):
        sub_pk = kwargs.get("subscription_pk")
        user = request.user
        subscription = user.subscriptions.get(pk=sub_pk)
        user.subscriptions.remove(subscription)
        user.save()
        return redirect('/accounts/subscribe/')
    

class SubscribeManageView(LoginRequiredMixin, UpdateView):
    '''
    구독 관리 View
    구독되어 있는 경우 해제
    구독안되어 있는 경우 추가
    '''
    model = User
    login_url = '/accounts/login/'
    template_name = 'blog/post_list.html'
    fields = ['subscriptions']

    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        '''
        post 요청이 올 경우
        현재 요청 유저의 subscriptions 목록을 확인하여
        목록에 포함되어 있는 경우 구독 해제
        목록에 없는 경우 구독
        '''
        subscription_pk = kwargs.get('pk')
        subscription_user = User.objects.get(pk=subscription_pk)
        current_user = request.user
        
        if subscription_user in current_user.subscriptions.all():
            current_user.subscriptions.remove(subscription_user)
        else:
            current_user.subscriptions.add(subscription_user)
        
        current_user.save()
        
        return HttpResponse('subscription manage success')



def passwordValidator(password1, password2):
    if password1 != password2:
        return '입력된 비밀번호가 다릅니다.'
    if len(password1) < 8:
        return '비밀번호는 8자리 이상이어야 합니다.'
    if not re.search(r"[a-zA-Z]", password1):
        return '비밀번호는 하나 이상의 영문이 포함되어야 합니다.'
    if not re.search(r"\d", password1):
        return '비밀번호는 하나 이상의 숫자가 포함되어야 합니다.'
    if not re.search(r"[!@#$%^&*()]", password1):
        return '비밀번호는 적어도 하나 이상의 특수문자(!@#$%^&*())가 포함되어야 합니다.'
    
login = CustomLoginView.as_view()
signup = SignUpView.as_view()
logout = CustomLogoutView.as_view()
profile = ProfileView.as_view()
profile_edit = ProfileEditView.as_view()
password_change = PasswordChangeView.as_view()
subscribe = SubscribeView.as_view()
subscribe_delete = SubscribeDeleteView.as_view()
subscribe_manage = SubscribeManageView.as_view()

templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no">
    <title>CORK Admin Template - Login Cover Page</title>
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'assets/img/favicon-32x32.png' %}">
    <link href="{% static 'assets/css/loader.css' %}" rel="stylesheet" type="text/css" />
    <script src="{% static 'assets/js/loader.js' %}"></script>
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href="https://fonts.googleapis.com/css?family=Quicksand:400,500,600,700&display=swap" rel="stylesheet">
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'assets/css/plugins.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'assets/css/authentication/form-1.css' %}" rel="stylesheet" type="text/css" />
    <!-- END GLOBAL MANDATORY STYLES -->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/forms/theme-checkbox-radio.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/forms/switches.css' %}">
</head>
<body class="form">
    
    <!-- BEGIN LOADER -->
    <div id="load_screen"> <div class="loader"> <div class="loader-content">
        <div class="spinner-grow align-self-center"></div>
    </div></div></div>
    <!--  END LOADER -->

    <div class="form-container justify-content-center">
        <div class="form-form">
            <div class="form-form-wrap">
                <div class="form-container">
                    <div class="form-content">

                        <h1 class="">Log In to <a href="{% url 'index' %}"><span class="brand-name">Tech_Blog</span></a></h1>
                        <p class="signup-link">새로 오셨나요? <a href="{% url 'accounts:signup' %}">계정 만들기</a></p>
                        <form class="text-left" method="post" action="{% url 'accounts:login' %}">
                            {% csrf_token %}
                            {% if form.errors %}
                                {% for filed in form %}
                                    {% for error in field.errors %}
                                        <div class="alert alert-danger">
                                            <strong>{{ field.label }}</strong>
                                            {{ error }}
                                        </div>
                                    {% endfor %}
                                {% endfor %}
                            {% endif %}
                            <div class="form">
                                <div id="username-field" class="field-wrapper input">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-at-sign"><circle cx="12" cy="12" r="4"></circle><path d="M16 8v5a3 3 0 0 0 6 0v-1a10 10 0 1 0-3.92 7.94"></path></svg>
                                    <input id="username" name="username" type="text" class="form-control" placeholder="Email" value="{{ form.username.value|default_if_none:'' }}">
                                </div>

                                <div id="password-field" class="field-wrapper input mb-2">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-lock"><rect x="3" y="11" width="18" height="11" rx="2" ry="2"></rect><path d="M7 11V7a5 5 0 0 1 10 0v4"></path></svg>
                                    <input id="password" name="password" type="password" class="form-control" placeholder="Password" value="{{ form.password.value|default_if_none:'' }}">
                                </div>
                                <div class="d-sm-flex justify-content-between">
                                    <div class="field-wrapper toggle-pass">
                                        <p class="d-inline-block">Show Password</p>
                                        <label class="switch s-primary">
                                            <input type="checkbox" id="toggle-password" class="d-none">
                                            <span class="slider round"></span>
                                        </label>
                                    </div>
                                    <div class="field-wrapper">
                                        <button type="submit" class="btn btn-primary" value="">Log In</button>
                                    </div>
                                    
                                </div>

                                <div class="field-wrapper">
                                    <a href="auth_pass_recovery.html" class="forgot-pass-link">Forgot Password?</a>
                                </div>

                            </div>
                        </form>

                    </div>                    
                </div>
            </div>
        </div>
    </div>

    
    <!-- BEGIN GLOBAL MANDATORY SCRIPTS -->
    <script src="{% static 'assets/js/libs/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    
    <!-- END GLOBAL MANDATORY SCRIPTS -->
    <script src="{% static 'assets/js/authentication/form-1.js' %}"></script>
    <script>
        var loaderElement = document.querySelector('#load_screen');
        setTimeout( function() {
            loaderElement.style.display = "none";
        }, 3000);
    </script>
</body>
</html>

templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="d-flex flex-column layout-top-spacing justify-content-between">
    <div class="page-header">
        <nav class="breadcrumb-one" aria-label="breadcrumb">
            <div class="title">
                <h3>User Profile</h3>
            </div>
        </nav>

    </div>

    <div class="form-container d-flex justify-content-center">
        <!-- Content -->
        <div class="form-form" style="width: 30rem;">
            <div class="form-form-wrap">
                <div class="user-profile">
                    <div class="widget-content widget-content-area">
                        <div class="d-flex justify-content-between">
                            <h3 class="">Info</h3>
                            <a href="{% url 'accounts:profile_edit' user.pk %}" class="mt-2 edit-profile"> <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit-3"><path d="M12 20h9"></path><path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z"></path></svg></a>
                        </div>
                        <div class="text-center user-info">
                            {% if user.profile_image %}
                                <img src="{{ user.profile_image.url }}" alt="avatar" width="100" height="100">
                            {% else %}
                                <!-- <img src="{% static 'assets/img/90x90.jpg' %}" alt="avatar"> -->
                                <svg xmlns="http://www.w3.org/2000/svg" width="60" height="60" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg>
                            {% endif %}
                            <p class="">{{ user.username }}</p>
                        </div>
                        <div class="user-info-list">
    
                            <ul class="contacts-block list-unstyled">
                                <li class="contacts-block__item">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg>{{ user.nickname }}
                                </li>
                                <li class="contacts-block__item">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-monitor"><rect x="2" y="3" width="20" height="14" rx="2" ry="2"></rect><line x1="8" y1="21" x2="16" y2="21"></line><line x1="12" y1="17" x2="12" y2="21"></line></svg>{{ user.development_field }}
                                </li>
                                <li class="contacts-block__item">
                                    <a href="mailto:example@mail.com"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-mail"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path><polyline points="22,6 12,13 2,6"></polyline></svg>{{ user.email }}</a>
                                </li>
                                <li class="contacts-block__item">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-phone"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"></path></svg>{{ user.phone }}
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="d-flex justify-content-end">
                    <a class="btn btn-primary mt-2" href="{% url 'accounts:password_change' %}">비밀번호 변경하기</a>
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock %}

templates/accounts/profile_edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="d-flex flex-column layout-top-spacing justify-content-between">
    <div class="page-header">
        <nav class="breadcrumb-one" aria-label="breadcrumb">
            <div class="title">
                <a href="{% url 'accounts:profile' %}"><h3>User Profile</h3></a>
            </div>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0);">Edit</a></li>
            </ol>
        </nav>
    </div>
    <div class="form-container justify-content-center">
        <div class="form-form w-100">
            <div class="form-form-wrap ms-10" style="width: 80rem;">
                <div class="form-container w-100">
                    <div class="form-content">
                        <form class="text-left"  method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% if notice %}
                            <div class="alert alert-light-danger border-0 mb-4" role="alert"> 
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"> 
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x close" data-dismiss="alert"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>
                                </button> 
                                <strong>{{ notice }}</strong>
                            </div>
                            {% endif %}
                            <div id="profile-image-field" class="field-wrapper input">
                                <div>
                                    {% if user.profile_image %}
                                    현재:<a href="{{ user.profile_image.url }}" id="current_profile_image">{{ user.profile_image }}</a><br>
                                    {% else %}
                                    현재:<br>
                                    {% endif %}
                                    변경:<input type="file" name="profile_image" accept="image/*" id="id_profile_image" class="p-0" value="{{ user.profile_image }}">
                                </div>
                            </div>
                            <div id="username-field" class="field-wrapper input">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg>
                                <input id="username" name="username" type="text" class="form-control" value="{{ user.username }}" readonly>
                            </div>
                            <div id="username-field" class="field-wrapper input">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg>
                                <input id="nickname" name="nickname" type="text" class="form-control" placeholder="닉네임" value="{{ user.nickname }}">
                            </div>
                            <div id="email-field" class="field-wrapper input">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-at-sign"><circle cx="12" cy="12" r="4"></circle><path d="M16 8v5a3 3 0 0 0 6 0v-1a10 10 0 1 0-3.92 7.94"></path></svg>
                                <input id="email" name="email" type="text" class="form-control" value="{{ user.email }}" readonly>
                            </div>
                            <div id="password-field d-flex justify-content-between" class="field-wrapper input mb-2">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-monitor"><rect x="2" y="3" width="20" height="14" rx="2" ry="2"></rect><line x1="8" y1="21" x2="16" y2="21"></line><line x1="12" y1="17" x2="12" y2="21"></line></svg>
                                <input id="development_field" name="development_field" type="text" class="form-control" placeholder="개발 분야" value="{{user.development_field}}">
                            </div>
                            <div id="password-field d-flex justify-content-between" class="field-wrapper input mb-2">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-phone"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"></path></svg>
                                <input id="phone" name="phone" type="text" class="form-control" placeholder="전화번호를 입력해주세요." value="{{user.phone}}">
                            </div>
                            <div class="d-sm-flex justify-content-end">
                                <div class="field-wrapper">
                                    <button type="submit" class="btn btn-primary" value="">변경사항 저장</button>
                                </div>
                            </div>
                        </form>

                    </div>                    
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
{% endblock %}