blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('list/<int:pk>/', views.postlist, name='postlist'),
    path('<int:pk>/', views.post_detail, name='post_detail'),
    path('edit/<int:pk>/', views.postedit, name='postedit'),
    path('write/', views.postwrite, name='postwrite'),
    path('delete/<int:pk>/', views.postdelete, name='postdelete'),
    path('search/<int:pk>/', views.postlist, name='postsearch'),
    path('comment_add/', views.comment_add, name='comment_add'),
    path('comment_delete/<int:comment_pk>/', views.comment_delete, name='comment_delete'),
    path('comment_edit/<int:pk>/', views.comment_edit, name='comment_edit'),
    path('recomment_add/', views.recomment_add, name='recomment_add'),
    path('recomment_delete/<int:recomment_pk>/', views.recomment_delete, name='recomment_delete'),
    path('recomment_eidt/<int:pk>/', views.recomment_edit, name='recomment_edit'),
    path('other/<int:other_pk>/', views.other_postlist, name='other_postlist'),
]

board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.board_list, name='board_list'),
    path('<int:pk>/', views.board_detail, name='board_detail'),
    path('write/', views.board_write, name='board_write'),
    path('edit/<int:pk>/', views.board_edit, name='board_edit'),
    path('delete/<int:pk>/', views.board_delete, name='board_delete'),
    path('comment/write/', views.comment_write, name='comment_write'),
    path('comment/edit/<int:pk>/', views.comment_edit, name='comment_edit'),
    path('comment/delete/<int:pk>/', views.comment_delete, name='comment_delete'),
    path('recomment/write/', views.recomment_write, name='recomment_write'),
    path('recomment/edit/<int:pk>/', views.recomment_edit, name='recomment_edit'),
    path('recomment/delete/<int:pk>/', views.recomment_delete, name='recomment_delete'),
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

tech_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('board/', include('board.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models

# Create your models here.

main/views.py
from typing import Any
from django.shortcuts import render
from django.views import View
from django.views.generic import ListView

from blog.models import Post
from board.models import Board_Post

class IndexView(ListView):

    def get(self, request):
        
        blog_post_list = Post.objects.all().order_by('-pk')[:8]
        subscription_post_list = []
        if request.user.is_authenticated:
            for subscription in request.user.subscriptions.all():
                subscription_post_list += Post.objects.filter(author = subscription).order_by('-pk')[:1]
        board_post_list = Board_Post.objects.all().order_by('-pk')[:8]
        context = {
            'blog_post_list': blog_post_list,
            'subscription_post_list': subscription_post_list,
            'board_post_list': board_post_list,
        }
        return render(request, 'main/index.html', context)

index = IndexView.as_view()

templates/main/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Blog Post BEGIN-->
<div class="page-header">
    <div class="page-title">
        <h3>Blog Post</h3>
    </div>
</div>
<div class="row layout-top-spacing">
    {% for blog_post in blog_post_list %}
        <div class = "col-xl-3 col-lg-6 col-md-6 col-sm-12 col-12 layout-spacing">
            <a href="{% url 'blog:post_detail' blog_post.pk %}">
                <div class="card component-card_9" role="navigation">
                    {% if blog_post.image %}
                        <img src="{{blog_post.image}}" class="card-img-top" alt="widget-card-2" style="height:24rem;">
                    {% else %}
                        <img src="{% static '/assets/img/ms-icon-310x310.png' %}" class="card-img-top" alt="widget-card-2" style="height:24rem;">
                    {% endif %}
                    <div class="card-body h-25">
                        <p class="meta-date">{{blog_post.created_at|date:"Y년 m월 j일"}}</p>
            
                        <h5 class="card-title">{{blog_post.title}}</h5>
            
                        <div class="meta-info">
                            <div class="mail-content-container mailInbox">
                                <div class="d-flex justify-content-between">
                                    <div class="d-flex user-info">
                                        <div class="f-head">
                                            {% if blog_post.author.profile_image %}
                                                <img src="{{ blog_post.author.profile_image.url }}" style="border-radius: 70%; width: 2rem; height: 2rem;" alt="avatar">
                                            {% else %}
                                                <svg xmlns="http://www.w3.org/2000/svg" width="2rem" height="2rem" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg>
                                            {% endif %}
                                        </div>
                                    </div>
                                    <div class="user-name">{{blog_post.author.username}}</div>
                                </div>
                            </div>
            
                            <div class="meta-action">
                                <div class="meta-view">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-eye"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg> {{blog_post.view_count}}
                                </div>
                            </div>
            
                        </div>
            
                    </div>
                </div>
            </a>
        </div>
    {% endfor %}
</div>
<!-- Blog Post END-->
<!-- Blog Post BEGIN-->
{% if user.is_authenticated %}
    <div class="page-header">
        <div class="page-title">
            <h3>Subscribe Post</h3>
        </div>
    </div>
    <div class="row layout-top-spacing">
        {% for subscription_post in subscription_post_list %}
            <div class = "col-xl-3 col-lg-6 col-md-6 col-sm-12 col-12 layout-spacing">
                <a href="{% url 'blog:post_detail' subscription_post.pk %}">
                    <div class="card component-card_9" role="navigation">
                        {% if subscription_post.image %}
                            <img src="{{subscription_post.image}}" class="card-img-top" alt="widget-card-2" style="height:24rem;">
                        {% else %}
                            <img src="{% static '/assets/img/ms-icon-310x310.png' %}" class="card-img-top" alt="widget-card-2" style="height:24rem;">
                        {% endif %}
                        <div class="card-body">
                            <p class="meta-date">{{subscription_post.created_at|date:"Y년 m월 j일"}}</p>
                
                            <h5 class="card-title">{{subscription_post.title}}</h5>
                
                            <div class="meta-info">
                                <div class="mail-content-container mailInbox">
                                    <div class="d-flex justify-content-between">
                                        <div class="d-flex user-info">
                                            <div class="f-head">
                                                {% if subscription_post.author.profile_image %}
                                                    <img src="{{ subscription_post.author.profile_image.url }}" style="border-radius: 70%; width: 2rem; height: 2rem;" alt="avatar">
                                                {% else %}
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="2rem" height="2rem" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg>
                                                {% endif %}
                                            </div>
                                        </div>
                                        <div class="user-name">{{subscription_post.author.username}}</div>
                                    </div>
                                </div>
                
                                <div class="meta-action">
                                    <div class="meta-view">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-eye"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg> {{subscription_post.view_count}}
                                    </div>
                                </div>
                
                            </div>
                
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
{% endif %}
<!-- Blog Post END-->
<!-- Dev Square Post BEGIN-->
<div class="page-header">
    <div class="page-title">
        <h3>Dev Square</h3>
    </div>
</div>
<div class="row layout-top-spacing">
    {% for board_post in board_post_list %}
        <div class = "col-xl-3 col-lg-6 col-md-6 col-sm-12 col-12 layout-spacing">
            <a href="{% url 'board:board_detail' board_post.pk %}">
                <div class="card component-card_9" role="navigation">
                    {% if board_post.image %}
                        <img src="{{board_post.image}}" class="card-img-top" alt="widget-card-2" style="height:24rem;">
                    {% else %}
                        <img src="{% static '/assets/img/ms-icon-310x310.png' %}" class="card-img-top" alt="widget-card-2" style="height:24rem;">
                    {% endif %}
                    <div class="card-body">
                        <p class="meta-date">{{board_post.created_at|date:"Y년 m월 j일"}}</p>
            
                        <h5 class="card-title">{{board_post.title}}</h5>
            
                        <div class="meta-info">
                            <div class="mail-content-container mailInbox">
                                <div class="d-flex justify-content-between">
                                    <div class="d-flex user-info">
                                        <div class="f-head">
                                            {% if board_post.author.profile_image %}
                                                <img src="{{ board_post.author.profile_image.url }}" style="border-radius: 70%; width: 2rem; height: 2rem;" alt="avatar">
                                            {% else %}
                                                <svg xmlns="http://www.w3.org/2000/svg" width="2rem" height="2rem" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg>
                                            {% endif %}
                                        </div>
                                    </div>
                                    <div class="user-name">{{board_post.author.username}}</div>
                                </div>
                            </div>
            
                            <div class="meta-action">
                                <div class="meta-view">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-eye"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg> {{board_post.view_count}}
                                </div>
                            </div>
            
                        </div>
            
                    </div>
                </div>
            </a>
        </div>
    {% endfor %}
</div>
<!-- Dev Square Post END-->
{% endblock %}