accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/<int:pk>/', views.profile_edit, name='profile_edit'),
    path('profile/password_change/', views.password_change, name='password_change'),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('subscribe/delete/<int:subscription_pk>/', views.subscribe_delete, name='subscribe_delete'),
    path('subscribe/manage/<int:pk>/', views.subscribe_manage, name='subscribe_manage'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('list/<int:pk>/', views.postlist, name='postlist'),
    path('<int:pk>/', views.post_detail, name='post_detail'),
    path('edit/<int:pk>/', views.postedit, name='postedit'),
    path('write/', views.postwrite, name='postwrite'),
    path('delete/<int:pk>/', views.postdelete, name='postdelete'),
    path('search/<int:pk>/', views.postlist, name='postsearch'),
    path('comment_add/', views.comment_add, name='comment_add'),
    path('comment_delete/<int:comment_pk>/', views.comment_delete, name='comment_delete'),
    path('comment_edit/<int:pk>/', views.comment_edit, name='comment_edit'),
    path('recomment_add/', views.recomment_add, name='recomment_add'),
    path('recomment_delete/<int:recomment_pk>/', views.recomment_delete, name='recomment_delete'),
    path('recomment_eidt/<int:pk>/', views.recomment_edit, name='recomment_edit'),
    path('other/<int:other_pk>/', views.other_postlist, name='other_postlist'),
]

board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.board_list, name='board_list'),
    path('<int:pk>/', views.board_detail, name='board_detail'),
    path('write/', views.board_write, name='board_write'),
    path('edit/<int:pk>/', views.board_edit, name='board_edit'),
    path('delete/<int:pk>/', views.board_delete, name='board_delete'),
    path('comment/write/', views.comment_write, name='comment_write'),
    path('comment/edit/<int:pk>/', views.comment_edit, name='comment_edit'),
    path('comment/delete/<int:pk>/', views.comment_delete, name='comment_delete'),
    path('recomment/write/', views.recomment_write, name='recomment_write'),
    path('recomment/edit/<int:pk>/', views.recomment_edit, name='recomment_edit'),
    path('recomment/delete/<int:pk>/', views.recomment_delete, name='recomment_delete'),
]

tech_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('board/', include('board.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
from django.db import models

class Board_Post(models.Model):
    title = models.CharField(max_length=100, null=False)
    content = models.TextField(null=False)
    category = models.CharField(max_length=100, null=False)
    upload_file = models.FileField(upload_to='board/files/%Y/%m/%d/', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    view_count = models.IntegerField(default=0, null=False)
    image = models.TextField(null=True)

    author = models.ForeignKey('accounts.User', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.title}'
    
    def get_absolute_url(self):
        return f'/board/{self.pk}/'
    
    def get_file_name(self):
        return self.upload_file.name.split('/')[-1]
    
    def get_file_ext(self):
        return self.get_file_name.split('.')[-1]
    

class Board_Comment(models.Model):
    content = models.CharField(max_length=500, null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    author = models.ForeignKey('accounts.User', on_delete=models.CASCADE)
    board_post = models.ForeignKey('Board_Post', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.author} :: {self.content}'
    
    def get_absolute_url(self):
        return self.board_post.get_absolute_url()


class Board_Recomment(models.Model):
    content = models.CharField(max_length=500, null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    author = models.ForeignKey('accounts.User', on_delete=models.CASCADE)
    board_comment = models.ForeignKey('Board_Comment', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.author} :: {self.content}'
    
    def get_absolute_url(self):
        return self.board_comment.get_absolute_url()

board/forms.py
from typing import Any
from django import forms
from django.forms import ModelForm

from .models import Board_Post, Board_Comment, Board_Recomment

class BoardWriteForm(ModelForm):
    '''
    게시판 게시글 작성 폼
    '''
    title = forms.CharField(max_length=100, error_messages={'required': '제목을 입력해주세요.'})
    content = forms.CharField(widget=forms.Textarea, error_messages={'required': '내용을 입력해주세요.'})

    class Meta:
        model = Board_Post
        fields = ['title', 'content', 'category', 'upload_file']


class BoardEditForm(ModelForm):
    '''
    게시판 게시글 수정 폼
    '''
    title = forms.CharField(max_length=100, error_messages={'required': '제목을 입력해주세요.'})
    content = forms.CharField(widget=forms.Textarea, error_messages={'required': '내용을 입력해주세요.'})

    class Meta:
        model = Board_Post
        fields = ['title', 'content', 'category', 'upload_file']


class CommentWriteForm(ModelForm):
    '''
    게시글 댓글 작성 폼
    '''
    content = forms.CharField(widget=forms.Textarea, error_messages={'required': '댓글을 입력해주세요.'})

    class Meta:
        model = Board_Comment
        fields = ['content']

    
class CommentEditForm(ModelForm):
    '''
    게시글 댓글 수정 폼
    '''
    content = forms.CharField(widget=forms.Textarea, error_messages={'required': '댓글을 입력해주세요.'})

    class Meta:
        model = Board_Comment
        fields = ['content']


class RecommentWriteForm(ModelForm):
    '''
    게시글 대댓글 작성 폼
    '''
    content = forms.CharField(widget=forms.Textarea, error_messages={'required': '답글을 입력해주세요.'})

    class Meta:
        model = Board_Recomment
        fields = ['content']


class RecommentEditForm(ModelForm):
    '''
    게시글 대댓글 수정 폼
    '''
    content = forms.CharField(widget=forms.Textarea, error_messages={'required': '답글을 입력해주세요.'})

    class Meta:
        model = Board_Recomment
        fields = ['content']

board/views.py
from typing import Any
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
import re

from .models import Board_Post, Board_Comment, Board_Recomment
from .forms import BoardWriteForm, BoardEditForm, CommentWriteForm, CommentEditForm, RecommentWriteForm, RecommentEditForm

class BoardListView(ListView):
    '''
    게시판 게시글 목록 View
    '''
    model = Board_Post
    ordering = '-pk'

    def get_queryset(self):
        querySet = super().get_queryset()
        search_keyword = self.request.GET.get('keyword')
        category = self.request.GET.get('category')
        if category == 'All':
            category = ''
        if search_keyword or category:
            querySet = querySet.filter(
                Q(title__icontains=search_keyword) | 
                Q(content__icontains=search_keyword) &
                Q(category__icontains=category)).distinct()
            
        return querySet


class BoardDetailView(DetailView):
    '''
    게시글 상세보기 View
    '''
    model = Board_Post

    def get(self, request, *args, **kwargs):
        '''
        상세보기 get 요청 시 조회수 증가
        '''
        board_post = Board_Post.objects.get(pk=self.kwargs['pk'])
        board_post.view_count += 1
        board_post.save()
        return super().get(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        '''
        context 반환 시 post의 댓글 & 대댓글을  context에 추가
        '''
        context = super().get_context_data(**kwargs)
        board_post = Board_Post.objects.get(pk=self.kwargs['pk'])
        comment_list = []
        for comment in Board_Comment.objects.filter(board_post=board_post):
            recomment = Board_Recomment.objects.filter(board_comment=comment)
            comment_list.append({
                'comment':comment,
                'recomments':recomment,
            })
        context['comment_list'] = comment_list
        return context


class BoardWriteView(LoginRequiredMixin, CreateView):
    '''
    게시판 글 작성 View
    '''
    login_url = '/accounts/login/'
    model = Board_Post
    form_class = BoardWriteForm

    def post(self, request, *args, **kwargs):
        form = BoardWriteForm(request.POST)
        if form.is_valid():
            board_post = form.save(commit=False)
            board_post.author = request.user
            board_post.image = extract_image(board_post.content)
            board_post.upload_file = request.FILES.get('upload_file')
            board_post.save()
            return redirect(board_post.get_absolute_url())
        return super().post(request, *args, **kwargs)
    

class BoardEditView(LoginRequiredMixin, UpdateView):
    '''
    게시판 게시글 수정 View
    '''
    login_url = '/accounts/login/'
    model = Board_Post
    form_class = BoardEditForm
    def post(self, request, *args, **kwargs):
        form = BoardEditForm(request.POST)
        print(form)
        if form.is_valid():
            board_post = Board_Post.objects.get(pk = self.kwargs["pk"])
            board_post.title = request.POST.get('title')
            board_post.content = request.POST.get('content')
            board_post.author = request.user
            image = extract_image(board_post.content)
            board_post.upload_file = request.FILES.get('upload_file')
            if image:
                board_post.image = image
            board_post.save()
            return redirect(board_post.get_absolute_url())
        return super().post(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['url'] = 'edit'
        return context


class BoardDeleteView(LoginRequiredMixin, DeleteView):
    '''
    게시글 삭제 View
    [x] success url 설정
    '''
    login_url = '/accounts/login/'
    model = Board_Post
    success_url = '/board/'


class CommentDeleteView(LoginRequiredMixin, DeleteView):
    '''
    게시글 댓글 삭제 View
    '''
    login_url = '/accounts/login/'
    model = Board_Comment
    
    def get_success_url(self):
        '''
        삭제 완료 시 redirect를 위한 success url
        '''
        post_pk = self.request.POST.get('post_pk')
        board_post = Board_Post.objects.get(pk=post_pk)
        return board_post.get_absolute_url()


class CommentEditView(LoginRequiredMixin, UpdateView):
    '''
    게시글 댓글 수정 View
    '''
    login_url = '/accounts/login/'
    model = Board_Comment
    form_class = CommentEditForm
    template_name = 'board/board_post_detail.html'

    def get_context_data(self, **kwargs):
        '''
        context 반환 시 post의 댓글 & 대댓글을  context에 추가
        '''
        context = super().get_context_data(**kwargs)
        board_post = Board_Post.objects.get(pk=self.request.POST['post_pk'])
        context['board_post'] = board_post
        comment_list = []
        for comment in Board_Comment.objects.filter(board_post=board_post):
            recomment = Board_Recomment.objects.filter(board_comment=comment)
            comment_list.append({
                'comment':comment,
                'recomments':recomment,
            })
        context['comment_list'] = comment_list
        return context


class CommentWriteView(LoginRequiredMixin, CreateView):
    '''
    게시글 댓글 작성 View
    '''
    login_url = '/accounts/login/'
    model = Board_Comment
    form_class = CommentWriteForm
    template_name = 'board/board_post_detail.html'

    def post(self, request, *args, **kwargs):
        '''
        댓글 작성 시 유효성을 검사
        유효성 통과 시 댓글을 저장
        '''
        form = CommentWriteForm(request.POST)
        board_post = Board_Post.objects.get(pk=request.POST['post_pk'])
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.board_post = board_post
            comment.save()
            return redirect(board_post.get_absolute_url())
        
        return super().post(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        '''
        context 반환 시 post의 댓글 & 대댓글을  context에 추가
        '''
        context = super().get_context_data(**kwargs)
        board_post = Board_Post.objects.get(pk=self.request.POST['post_pk'])
        context['board_post'] = board_post
        comment_list = []
        for comment in Board_Comment.objects.filter(board_post=board_post):
            recomment = Board_Recomment.objects.filter(board_comment=comment)
            comment_list.append({
                'comment':comment,
                'recomments':recomment,
            })
        context['comment_list'] = comment_list
        return context


class RecommentWriteView(LoginRequiredMixin, CreateView):
    '''
    게시글 대댓글 작성 View
    [x] 대댓글 작성 구현 필요
    '''
    login_url = '/accounts/login'
    model = Board_Recomment
    form_class = RecommentWriteForm
    template_name = 'board/board_post_detail.html'

    def post(self, request, *args, **kwargs):
        form = RecommentWriteForm(request.POST)
        if form.is_valid():
            recomment = form.save(commit=False)
            recomment.author = request.user
            recomment.board_comment = Board_Comment.objects.get(pk=request.POST['comment_pk'])
            recomment.save()
            return redirect(recomment.get_absolute_url())
        return super().post(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        '''
        context 반환 시 post의 댓글 & 대댓글을  context에 추가
        '''
        context = super().get_context_data(**kwargs)
        board_post = Board_Post.objects.get(pk=self.request.POST['post_pk'])
        context['board_post'] = board_post
        comment_list = []
        for comment in Board_Comment.objects.filter(board_post=board_post):
            recomment = Board_Recomment.objects.filter(board_comment=comment)
            comment_list.append({
                'comment':comment,
                'recomments':recomment,
            })
        context['comment_list'] = comment_list
        return context


class RecommentEditView(LoginRequiredMixin, UpdateView):
    '''
    게시판 대댓글 수정 View
    '''
    login_url = '/accounts/login'
    model = Board_Recomment
    form_class = RecommentEditForm
    template_name = 'board/board_post_detail.html'

    def get_context_data(self, **kwargs):
        '''
        context 반환 시 post의 댓글 & 대댓글을  context에 추가
        '''
        context = super().get_context_data(**kwargs)
        board_post = Board_Post.objects.get(pk=self.request.POST['post_pk'])
        context['board_post'] = board_post
        comment_list = []
        for comment in Board_Comment.objects.filter(board_post=board_post):
            recomment = Board_Recomment.objects.filter(board_comment=comment)
            comment_list.append({
                'comment':comment,
                'recomments':recomment,
            })
        context['comment_list'] = comment_list
        return context


class RecommentDeleteView(LoginRequiredMixin, DeleteView):
    '''
    게시판 대댓글 삭제 View
    '''
    login_url = '/accounts/login/'
    model = Board_Recomment

    def get_success_url(self):
        '''
        삭제 완료 시 redirect를 위한 success url
        '''
        post_pk = self.request.POST.get('post_pk')
        board_post = Board_Post.objects.get(pk=post_pk)
        return board_post.get_absolute_url()


board_list = BoardListView.as_view()
board_detail = BoardDetailView.as_view()
board_write = BoardWriteView.as_view()
board_edit = BoardEditView.as_view()
board_delete = BoardDeleteView.as_view()
comment_write = CommentWriteView.as_view()
comment_edit = CommentEditView.as_view()
comment_delete = CommentDeleteView.as_view()
recomment_write = RecommentWriteView.as_view()
recomment_edit = RecommentEditView.as_view()
recomment_delete = RecommentDeleteView.as_view()

def extract_image(content):
    '''

templates/board/board_base.html
{% extends 'base.html' %}
{% load static %}
{% block navbar %}
    <div class="nav-logo align-self-center">
        <a class="navbar-brand" href="{% url 'index' %}"><img alt="logo" src="{% static 'assets/img/favicon-96x96.png' %}"> <span class="navbar-brand-name">Tech_Blog</span></a>
    </div>
    <ul class="navbar-item topbar-navigation">
        
        <!--  BEGIN TOPBAR  -->
        <div class="topbar-nav header navbar" role="banner">
            <nav id="topbar">

                <ul class="list-unstyled menu-categories" id="topAccordion">
                    {% if user.is_authenticated %}
                    <li class="menu single-menu">
                        <a href="{% url 'blog:postlist' user.pk %}" aria-expanded="false" class="dropdown-toggle autodroprown" id="blog_menu_a">
                            <div class="">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                                
                                <span>My Blog</span>
                            </div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-down"><polyline points="6 9 12 15 18 9"></polyline></svg>
                        </a>
                    </li>
                    
                    <li class="menu single-menu">
                        <a href="{% url 'accounts:subscribe' %}" aria-expanded="false" class="dropdown-toggle autodroprown">
                            <div class="">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-coffee">
                                <path d="M18 8h1a4 4 0 0 1 0 8h-1"></path>
                                <path d="M2 8h16v9a4 4 0 0 1-4 4H6a4 4 0 0 1-4-4V8z"></path>
                                <line x1="6" y1="1" x2="6" y2="4"></line>
                                <line x1="10" y1="1" x2="10" y2="4"></line>
                                <line x1="14" y1="1" x2="14" y2="4"></line>
                                </svg>
                                <span>Subscribe</span>
                            </div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-down"><polyline points="6 9 12 15 18 9"></polyline></svg>
                        </a>
                    </li>
                    {% endif %}
                    <li class="menu single-menu active">
                        <a href="{% url 'board:board_list' %}" aria-expanded="false" class="dropdown-toggle autodroprown">
                            <div class="">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-message-square"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path></svg>
                                
                                <span>Dev Square</span>
                            </div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-down"><polyline points="6 9 12 15 18 9"></polyline></svg>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
        <!--  END TOPBAR  -->

    </ul>
    {% if user.is_authenticated %}
    <ul class="navbar-item flex-row ml-auto">
        <li class="nav-item align-self-center search-animated">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-search toggle-search"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>
            <form class="form-inline search-full form-inline search" role="search">
                <div class="search-bar">
                    <input type="text" class="form-control search-form-control  ml-lg-auto" placeholder="Search...">
                </div>
            </form>
        </li>
    </ul>
    <ul class="navbar-item flex-row nav-dropdowns">

        <li class="nav-item dropdown user-profile-dropdown order-lg-0 order-1">
            <a href="javascript:void(0);" class="nav-link dropdown-toggle user" id="user-profile-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {% if user.profile_image %}
                <div class="media">
                    <img src="{{ user.profile_image.url }}" class="img-fluid" alt="admin-profile">
                </div>
                {% else %}
                <div class="media">
                    <img src="{% static 'assets/img/90x90.jpg' %}" class="img-fluid" alt="admin-profile">
                </div>
                {% endif %}
            </a>
            <div class="dropdown-menu position-absolute" aria-labelledby="userProfileDropdown">
                <div class="user-profile-section">
                    <div class="media mx-auto">
                        <div class="media-body">
                            <h5>{{ user.username }}</h5>
                            <p>{{ user.development_field }}</p>
                        </div>
                    </div>
                </div>
                <div class="dropdown-item">
                    <a href="{% url 'accounts:profile' %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg> <span>Profile</span>
                    </a>
                </div>
                <div class="dropdown-item">
                    <a href="{% url 'accounts:logout' %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-log-out"><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path><polyline points="16 17 21 12 16 7"></polyline><line x1="21" y1="12" x2="9" y2="12"></line></svg> <span>Log Out</span>
                    </a>
                </div>
            </div>

        </li>
    </ul>
    {% else %}
    <ul class="d-flex justify-content-end align-items-center w-100">
        
            <a class="btn btn-primary mt-2" href="{% url 'accounts:login' %}">로그인</a>
        
    </ul>
    {% endif %}
{% endblock %}

templates/board/board_post_list.html
{% extends 'board/board_base.html' %}
{% load static %}
{% block content %}
<div class="page-header">
    <nav class="breadcrumb-one" aria-label="breadcrumb">
        <div class="title">
            <h3>Dev Square</h3>
        </div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">List</li>
        </ol>
    </nav>
</div>

<div class="row layout-top-spacing">
    <div class="col-xl-12 col-lg-12 col-md-12">

        <div class="row">

            <div class="col-xl-12  col-md-12">

                <div class="mail-box-container">
                    <div class="mail-overlay"></div>
                    {% if user.is_authenticated %}
                    <div class="tab-title">
                        <div class="row">
                            <div class="col-md-12 col-sm-12 col-12 text-center mail-btn-container">
                                <a id="btn-compose-mail" class="btn btn-block" href="{% url 'board:board_write' %}"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus"><line x1="12" y1="5" x2="12" y2="19"></line><line x1="5" y1="12" x2="19" y2="12"></line></svg></a>
                            </div>
                        </div>
                    </div>
                    {% endif %}

                    <div id="mailbox-inbox" class="accordion mailbox-inbox">

                        <form class="search" action="{% url 'board:board_list' %}" method="get">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-menu mail-menu d-lg-none"><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg>
                            <input type="text" class="form-control input-search" placeholder="Search Here..." name="keyword">
                            <select class="m-0 border-0" id="" placeholder="카테고리를 선택하세요." name="category">
                                <option value="All">All</option>
                                <option value="Backend">Backend</option>
                                <option value="Frontend">Frontend</option>
                            </select>
                        </form>
                        
                        <!-- My Blog 게시글 리스트 BEGIN -->
                        
                        <div class="message-box">
                            
                            <div class="message-box-scroll" id="ct">
                                {% for post in board_post_list %}
                                <a href="{% url 'board:board_detail' post.id %}">
                                    <div class="mail-item draft">
                                        <div class="animated animatedFadeInUp fadeInUp" id="mailHeadingOne">
                                            <div class="mb-0">
                                                <div class="mail-item-heading personal collapsed"  data-toggle="collapse" role="navigation" data-target="#mailCollapseOne" aria-expanded="false">
                                                    <div class="mail-item-inner">
    
                                                        <div class="d-flex">
                                                            <div class="f-body" data-mailfrom="info@mail.com" data-mailto="kf@mail.com" data-mailcc="">
                                                                <div class="meta-title-tag">
                                                                    <p class="user-email p-0" style="width: 5%;">{{ post.author }}</p>
                                                                    <p class="mail-content-excerpt"><span class="mail-title" data-mailTitle="Web Design News">{{ post.title }}</p>
                                                                    <div class="tags">
                                                                        {{ post.category }}
                                                                    </div>
                                                                    <p class="meta-time align-self-center">작성일 : {{ post.created_at|date:"Y/m/j" }}</p>
                                                                    <p class="meta-time align-self-center">수정일 :{{ post.updated_at|date:"Y/m/j" }}</p>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </a>
                                {% endfor %}
                            </div>
                        </div>
                        
                        <!-- My Blog 게시글 리스트 END -->
                        
                    </div>
                    
                </div>

            </div>


        </div>

    </div>
</div>
{% endblock %}